// priority: 1000
StartupEvents.registry('item', event => {
    event.create('counterweight_gear').texture('kubejs:item/materials/counterweight_gear').tag('kubejs:unstable')
    event.create('oracle_gate').texture('kubejs:item/materials/oracle_gate').tag('kubejs:unstable')
    event.create('simulated_unit').texture('kubejs:item/materials/simulated_unit').tag('kubejs:unstable')
    event.create('redstone_capacitor').texture('kubejs:item/materials/redstone_capacitor')
    event.create('random_tick_spring').texture('kubejs:item/materials/random_tick_spring').tag('kubejs:unstable')
    event.create('structural_bolt').texture('kubejs:item/materials/structural_bolt')
    event.create('unstable_matter').texture('kubejs:item/materials/unstable_matter').fireResistant().tag('kubejs:unstable')
    event.create('refined_brass_ingot').texture('kubejs:item/materials/refined_brass_ingot').tag('kubejs:unstable')
    event.create('reverse_causality_chip').texture('kubejs:item/materials/reverse_causality_chip').tag('kubejs:unstable')
    event.create('timing_valve').texture('kubejs:item/materials/timing_valve').tag('kubejs:unstable')
    event.create('stable_substrate').texture('kubejs:item/materials/stable_substrate')
    event.create('amethyst_resonator').texture('kubejs:item/materials/amethyst_resonator')
    event.create('mantle_ore').texture('kubejs:item/materials/mantle_ore').maxStackSize(1)
    event.create('colorful_dye').texture('kubejs:item/materials/colorful_dye')
    event.create('colorful_slime_ball').texture('kubejs:item/materials/colorful_slime_ball')
    event.create('colorful_singularity').texture('kubejs:item/materials/colorful_singularity')
})