// priority: 1000
StartupEvents.registry('fluid', event => {
	event.create('melted_dark_iron')
		.thickTexture(0x3b3b3b)
		.bucketColor(0x3b3b3b)
	event.create('melted_witherite')
		.thickTexture(0xF86A1D)
		.bucketColor(0xF86A1D)
	event.create('melted_ancient_metal')
		.thickTexture(0xD8B669)
		.bucketColor(0xD8B669)
	event.create('melted_black_steel')
		.thickTexture(0x2C303C)
		.bucketColor(0x2C303C)
	event.create('melted_ignitium')
		.thickTexture(0xFCF546)
		.bucketColor(0xFCF546)
	event.create('melted_cursium')
		.thickTexture(0x55E9CA)
		.bucketColor(0x55E9CA)
	event.create('melted_platinum')
		.thickTexture(0x8FAAAA)
		.bucketColor(0x8FAAAA)
	event.create('melted_rose_quartz')
		.thickTexture(0xFF3F7F)
		.bucketColor(0xFF3F7F)
})
