// priority: 1000
StartupEvents.registry('fluid', event => {
	event.create('melted_dark_iron')
		.thickTexture(0x3b3b3b)
		.bucketColor(0x3b3b3b)
	event.create('melted_witherite')
		.thickTexture(0x3b3b3b)
		.bucketColor(0x3b3b3b)	
	event.create('melted_ancient_metal')
		.thickTexture(0xdaa45a)
		.bucketColor(0xdaa45a)	
	event.create('melted_black_steel')
		.thickTexture(0xdaa45a)
		.bucketColor(0xdaa45a)
	event.create('melted_ignitium')
		.thickTexture(0xdaa45a)
		.bucketColor(0xdaa45a)	
	event.create('melted_patterned')
		.thickTexture(0xdaa45a)
		.bucketColor(0xdaa45a)	
	event.create('melted_cursium')
		.thickTexture(0xdaa45a)
		.bucketColor(0xdaa45a)	
})