// priority: 500
RegistryOrgan('kubejs:appendix').addScore('chestcavity:luck', 1)
RegistryOrgan('kubejs:intestine').addScore('chestcavity:nutrition', 1)
RegistryOrgan('kubejs:heart').addScore('chestcavity:health', 1)
RegistryOrgan('kubejs:kidney').addScore('chestcavity:filtration', 1)
RegistryOrgan('kubejs:liver').addScore('chestcavity:detoxification', 1)
RegistryOrgan('kubejs:lung').addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1)
RegistryOrgan('kubejs:muscle').addScore('chestcavity:strength', 1)
RegistryOrgan('kubejs:rib').addScore('chestcavity:defense', 1)
RegistryOrgan('kubejs:spine').addScore('chestcavity:nerves', 1)
RegistryOrgan('kubejs:spleen').addScore('chestcavity:metabolism', 1)
RegistryOrgan('kubejs:stomach').addScore('chestcavity:digestion', 1)

RegistryOrgan('kubejs:animal_appendix').addScore('chestcavity:luck', 0.5)
RegistryOrgan('kubejs:animal_intestine').addScore('chestcavity:nutrition', 1).addScore('chestcavity:digestion', 0.5)
RegistryOrgan('kubejs:animal_heart').addScore('chestcavity:health', 1)
RegistryOrgan('kubejs:animal_kidney').addScore('chestcavity:filtration', 1)
RegistryOrgan('kubejs:animal_liver').addScore('chestcavity:detoxification', 1)
RegistryOrgan('kubejs:animal_lung').addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1.5)
RegistryOrgan('kubejs:animal_muscle').addScore('chestcavity:strength', 1)
RegistryOrgan('kubejs:animal_rib').addScore('chestcavity:defense', 1)
RegistryOrgan('kubejs:animal_spine').addScore('chestcavity:nerves', 1).addScore('chestcavity:defense', 0.5)
RegistryOrgan('kubejs:animal_spleen').addScore('chestcavity:metabolism', 1)
RegistryOrgan('kubejs:animal_stomach').addScore('chestcavity:digestion', 1.5)


RegistryOrgan('kubejs:insect_lung').addScore('chestcavity:breath_recovery', 1).addScore('chestcavity:breath_capacity', 1).addScore('chestcavity:endurance', 1)
RegistryOrgan('kubejs:insect_muscle').addScore('chestcavity:strength', 1.5)
RegistryOrgan('kubejs:insect_intestine').addScore('chestcavity:nutrition', 1.5)
RegistryOrgan('kubejs:insect_heart').addScore('chestcavity:health', 1)
RegistryOrgan('kubejs:insect_caeca').addScore('chestcavity:metabolism', 1)
RegistryOrgan('kubejs:insect_stomach').addScore('chestcavity:digestion', 1)