// priority: 998
const IsLoadedKubeloader = Platform.isLoaded('kubeloader')

if (IsLoadedKubeloader) {
    ContentPacks.putShared('RegistryTitleJson', RegistryTitleJson)
    ContentPacks.putShared('TitleJsonModel', TitleJsonModel)
    ContentPacks.putShared('RegistryOrganStrategy', RegistryOrganStrategy)
    ContentPacks.putShared('OrganStrategyModel', OrganStrategyModel)
    ContentPacks.putShared('RegistryAttributeIdentifier', RegistryAttributeIdentifier)
    ContentPacks.putShared('AttributeUUIDModel', AttributeUUIDModel)
    ContentPacks.putShared('RegistryOrgan', RegistryOrgan)
    ContentPacks.putShared('RegistryPseudoOrgan', RegistryPseudoOrgan)
    ContentPacks.putShared('OrganItemModel', OrganItemModel)
    ContentPacks.putShared('RegistryOriginChangedStrategy', RegistryOriginChangedStrategy)
    ContentPacks.putShared('SlotStrategyModel', SlotStrategyModel)
    ContentPacks.putShared('OrganArsEffectResolvePre', OrganArsEffectResolvePre)
    ContentPacks.putShared('OrganArsEffectResolvePost', OrganArsEffectResolvePost)
    ContentPacks.putShared('OrgaDecorateChatEvent', OrgaDecorateChatEvent)
    ContentPacks.putShared('OrganISSEntitySpellCastEvent', OrganISSEntitySpellCastEvent)
    ContentPacks.putShared('OrganISSPlayerSpellCastEvent', OrganISSPlayerSpellCastEvent)
    ContentPacks.putShared('OrganISSSpellLevelModifyEvent', OrganISSSpellLevelModifyEvent)
    ContentPacks.putShared('OrganISSSpellSelectionEvent', OrganISSSpellSelectionEvent)
    ContentPacks.putShared('OrganShieldBlockEvent', OrganShieldBlockEvent)
    ContentPacks.putShared('OrganAddStatusEffectEvent', OrganAddStatusEffectEvent)
    ContentPacks.putShared('OrganBlockBrokenEvent', OrganBlockBrokenEvent)
    ContentPacks.putShared('OrganChestCavityUpdateStrategy', OrganChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganTakeOnStrategy', OrganTakeOnStrategy)
    ContentPacks.putShared('OrganTakeOffStrategy', OrganTakeOffStrategy)
    ContentPacks.putShared('SlotChestCavityUpdateStrategy', SlotChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganChestLootEvent', OrganChestLootEvent)
    ContentPacks.putShared('OrganEntityBeHurtEvent', OrganEntityBeHurtEvent)
    ContentPacks.putShared('OrganEntityDeathEvent', OrganEntityDeathEvent)
    ContentPacks.putShared('OrganEntityDoDamageEvent', OrganEntityDoDamageEvent)
    ContentPacks.putShared('OrganEntityLootEvent', OrganEntityLootEvent)
    ContentPacks.putShared('OrganEntityTickEvent', OrganEntityTickEvent)
    ContentPacks.putShared('OrganFoodEatenEvent', OrganFoodEatenEvent)
    ContentPacks.putShared('OrganItemRightClickedEvent', OrganItemRightClickedEvent)
    ContentPacks.putShared('OrganKeyBindEvent', OrganKeyBindEvent)
    ContentPacks.putShared('OrganPlayerEnchantEvent', OrganPlayerEnchantEvent)
}