// priority, 998
const IsLoadedKubeloader = Platform.isLoaded('kubeloader')

if (IsLoadedKubeloader) {
    ContentPacks.putShared('RegisterTitleJson', RegisterTitleJson)
    ContentPacks.putShared('TitleJsonModel', TitleJsonModel)
    ContentPacks.putShared('RegistryOrganStrategy', RegistryOrganStrategy)
    ContentPacks.putShared('OrganStrategyModel', OrganStrategyModel)
    ContentPacks.putShared('RegistryAttributeIdentifier', RegistryAttributeIdentifier)
    ContentPacks.putShared('AttributeUUIDModel', AttributeUUIDModel)
    ContentPacks.putShared('RegistryOrgan', RegistryOrgan)
    ContentPacks.putShared('RegistryPseudoOrgan', RegistryPseudoOrgan)
    ContentPacks.putShared('OrganItemModel', OrganItemModel)
    ContentPacks.putShared('DungeonWaveModel', DungeonWaveModel)
    ContentPacks.putShared('DungeonEventActionModel', DungeonEventActionModel)
    ContentPacks.putShared('NewKillAmountWave', NewKillAmountWave)
    ContentPacks.putShared('NewContinousKillAmountWave', NewContinousKillAmountWave)
    ContentPacks.putShared('RegisterOrganScoreGoopRenderStrategy', RegisterOrganScoreGoopRenderStrategy)
    ContentPacks.putShared('RegisterOriginChangedStrategy', RegisterOriginChangedStrategy)
    ContentPacks.putShared('SlotStrategyModel', SlotStrategyModel)
    ContentPacks.putShared('OrganBlockBrokenEvent', OrganBlockBrokenEvent)
    ContentPacks.putShared('OrganChestCavityUpdateStrategy', OrganChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganTakeOnStrategy', OrganTakeOnStrategy)
    ContentPacks.putShared('OrganTakeOffStrategy', OrganTakeOffStrategy)
    ContentPacks.putShared('SlotChestCavityUpdateStrategy', SlotChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganChestLootEvent', OrganChestLootEvent)
    ContentPacks.putShared('OrganEntityBeHurtEvent', OrganEntityBeHurtEvent)
    ContentPacks.putShared('OrganEntityDeathEvent', OrganEntityDeathEvent)
    ContentPacks.putShared('OrganEntityDoDamageEvent', OrganEntityDoDamageEvent)
    ContentPacks.putShared('OrganEntityLootEvent', OrganEntityLootEvent)
    ContentPacks.putShared('OrganEntityTickEvent', OrganEntityTickEvent)
    ContentPacks.putShared('OrganFoodEatenEvent', OrganFoodEatenEvent)
    ContentPacks.putShared('OrganItemRightClickedEvent', OrganItemRightClickedEvent)
    ContentPacks.putShared('OrganKeyBindEvent', OrganKeyBindEvent)
    ContentPacks.putShared('OrganPlayerEnchantEvent', OrganPlayerEnchantEvent)
    ContentPacks.putShared('PlayerSpellCastEvent', ISSPlayerSpellCastEvent)
    ContentPacks.putShared('OrganSpellLevelModifyEvent', ISSSpellLevelModifyEvent)
    ContentPacks.putShared('OrganSpellSelectionEvent', ISSSpellSelectionEvent)
    ContentPacks.putShared('OrganScoreGoopRenderStrategy', OrganScoreGoopRenderStrategy)
}