// priority: 500
const IsLoadedKubeloader = Platform.isLoaded('kubeloader')

if (IsLoadedKubeloader) {
    ContentPacks.putShared('RegistryOrganStrategy', RegistryOrganStrategy)
    ContentPacks.putShared('OrganStrategyModel', OrganStrategyModel)
    ContentPacks.putShared('OrganEventModel', OrganEventModel)
    ContentPacks.putShared('SlotStrategyModel', SlotStrategyModel)
    ContentPacks.putShared('AttributeUUIDModel', AttributeUUIDModel)
    ContentPacks.putShared('AttributeManagerModel', AttributeManagerModel)
    ContentPacks.putShared('PiecewiseMappingModel', PiecewiseMappingModel)
    ContentPacks.putShared('PriorityStrategyModel', PriorityStrategyModel)
    ContentPacks.putShared('StrategyModel', StrategyModel)
    ContentPacks.putShared('StandardWaveEntityItemModel', StandardWaveEntityItemModel)
    ContentPacks.putShared('WeightRandomItem', WeightRandomItem)
    ContentPacks.putShared('WeightRandomModel', WeightRandomModel)

    ContentPacks.putShared('RegistryAttributeIdentifier', RegistryAttributeIdentifier)
    ContentPacks.putShared('RegistryOrgan', RegistryOrgan)
    ContentPacks.putShared('RegistryPseudoOrgan', RegistryPseudoOrgan)
    ContentPacks.putShared('RegistryOriginChangedStrategy', RegistryOriginChangedStrategy)
    ContentPacks.putShared('RegistryOrganScoreAttribute', RegistryOrganScoreAttribute)

    ContentPacks.putShared('TumorMutationConfigModel', TumorMutationConfigModel)
    ContentPacks.putShared('RegistryTumorMutationConfig', RegistryTumorMutationConfig)
    ContentPacks.putShared('UnformedTumorFluidConfigModel', UnformedTumorFluidConfigModel)
    ContentPacks.putShared('RegistryUnformedTumorFluidConfig', RegistryUnformedTumorFluidConfig)

    ContentPacks.putShared('GatewawyTypeStackRewardMappingModel', GatewawyTypeStackRewardMappingModel)
    ContentPacks.putShared('GatewawyExtractantMaterialWeightModel', GatewawyExtractantMaterialWeightModel)
    ContentPacks.putShared('GatewawyAuxiliaryMaterialWeightModel', GatewawyAuxiliaryMaterialWeightModel)
    ContentPacks.putShared('GatewawySpecialAwakeStoneWeightModel', GatewawySpecialAwakeStoneWeightModel)
    ContentPacks.putShared('RegistryGatewayExtractantStrategy', RegistryGatewayExtractantStrategy)
    ContentPacks.putShared('ArtificalTicketConvertConfigModel', ArtificalTicketConvertConfigModel)
    ContentPacks.putShared('RegistryArtificalTicketConvertConfig', RegistryArtificalTicketConvertConfig)
    ContentPacks.putShared('GatewayWaveEntityMapping', GatewayWaveEntityMapping)
    ContentPacks.putShared('GatewayChaosModifierMapping', GatewayChaosModifierMapping)


    ContentPacks.putShared('OrganArsEffectResolvePre', OrganArsEffectResolvePre)
    ContentPacks.putShared('OrganArsEffectResolvePost', OrganArsEffectResolvePost)
    ContentPacks.putShared('OrgaDecorateChatEvent', OrgaDecorateChatEvent)
    ContentPacks.putShared('OrganISSEntitySpellCastEvent', OrganISSEntitySpellCastEvent)
    ContentPacks.putShared('OrganISSPlayerSpellCastEvent', OrganISSPlayerSpellCastEvent)
    ContentPacks.putShared('OrganISSSpellLevelModifyEvent', OrganISSSpellLevelModifyEvent)
    ContentPacks.putShared('OrganISSSpellSelectionEvent', OrganISSSpellSelectionEvent)
    ContentPacks.putShared('OrganShieldBlockEvent', OrganShieldBlockEvent)
    ContentPacks.putShared('OrganAddStatusEffectEvent', OrganAddStatusEffectEvent)
    ContentPacks.putShared('OrganBlockBrokenEvent', OrganBlockBrokenEvent)
    ContentPacks.putShared('OrganBlockRightClickedEvent', OrganBlockRightClickedEvent)
    ContentPacks.putShared('OrganChestCavityUpdateStrategy', OrganChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganTakeOnStrategy', OrganTakeOnStrategy)
    ContentPacks.putShared('OrganTakeOffStrategy', OrganTakeOffStrategy)
    ContentPacks.putShared('SlotChestCavityUpdateStrategy', SlotChestCavityUpdateStrategy)
    ContentPacks.putShared('OrganChestLootEvent', OrganChestLootEvent)
    ContentPacks.putShared('OrganEntityBeHurtEvent', OrganEntityBeHurtEvent)
    ContentPacks.putShared('OrganEntityDeathEvent', OrganEntityDeathEvent)
    ContentPacks.putShared('OrganEntityKillEvent', OrganEntityKillEvent)
    ContentPacks.putShared('OrganEntityDoDamageEvent', OrganEntityDoDamageEvent)
    ContentPacks.putShared('OrganEntityLootEvent', OrganEntityLootEvent)
    ContentPacks.putShared('OrganEntityTickEvent', OrganEntityTickEvent)
    ContentPacks.putShared('OrganFoodEatenEvent', OrganFoodEatenEvent)
    ContentPacks.putShared('OrganItemRightClickedEvent', OrganItemRightClickedEvent)
    ContentPacks.putShared('OrganKeyBindEvent', OrganKeyBindEvent)
    ContentPacks.putShared('OrganPlayerEnchantEvent', OrganPlayerEnchantEvent)
    ContentPacks.putShared('OrganEntityInteractEvent', OrganEntityInteractEvent)
    ContentPacks.putShared('OrganEntityBeInteractedEvent', OrganEntityBeInteractedEvent)
    ContentPacks.putShared('ExposureModifyFrame', ExposureModifyFrame)
}