// priority: 1000
StartupEvents.registry('item', event => {
    event.create('gateways_auxiliary_material_1').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_1').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_2').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_2').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_3').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_3').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_4').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_4').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_5').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_5').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_6').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_6').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_7').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_7').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_8').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_8').tag('kubejs:gateways_auxiliary_material')
    event.create('gateways_auxiliary_material_9').maxStackSize(1).texture('kubejs:item/materials/gateways_auxiliary_material_9').tag('kubejs:gateways_auxiliary_material')

    event.create('gateways_awake_stone_1').texture('kubejs:item/materials/gateways_awake_stone_1').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_2').texture('kubejs:item/materials/gateways_awake_stone_2').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_3').texture('kubejs:item/materials/gateways_awake_stone_3').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_4').texture('kubejs:item/materials/gateways_awake_stone_4').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_5').texture('kubejs:item/materials/gateways_awake_stone_5').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_6').texture('kubejs:item/materials/gateways_awake_stone_6').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_7').texture('kubejs:item/materials/gateways_awake_stone_7').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_8').texture('kubejs:item/materials/gateways_awake_stone_8').tag('kubejs:gateways_awake_stone')
    event.create('gateways_awake_stone_9').texture('kubejs:item/materials/gateways_awake_stone_9').tag('kubejs:gateways_awake_stone')

    event.create('gateways_extractant_material_1').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_1').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_2').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_2').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_3').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_3').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_4').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_4').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_5').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_5').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_6').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_6').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_7').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_7').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_8').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_8').tag('kubejs:gateways_extractant_material')
    event.create('gateways_extractant_material_9').maxStackSize(1).maxDamage(10).texture('kubejs:item/materials/gateways_extractant_material_9').tag('kubejs:gateways_extractant_material')
})