// priority: 2000
const GraveyardAdvanceArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '          G          ',)
    .aisle('      BBSBSBSBB      ', '          L          ',)
    .aisle('    BBSSSBSBSSSBB    ', '                     ',)
    .aisle('   BSSSSSBSBSSSSSB   ', '                     ',)
    .aisle('  BSSSSSSBSBSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSBSBSSSSSSB  ', '                     ',)
    .aisle(' BSSSSSDDBSBDDSSSSSB ', '                     ',)
    .aisle(' BSSSSDDBBBBBDDSSSSB ', '                     ',)
    .aisle('BSSSSSDBBDDDBBDSSSSSB', '        O   O        ',)
    .aisle('BBBBBBBBDDADDBBBBBBBB', '                     ',)
    .aisle('BSSSSSSBDACADBSSSSSSB', 'GL        @        LG',)
    .aisle('BBBBBBBBDDADDBBBBBBBB', '                     ',)
    .aisle('BSSSSSDBBDDDBBDSSSSSB', '        O   O        ',)
    .aisle(' BSSSSDDBBBBBDDSSSSB ', '                     ',)
    .aisle(' BSSSSSDDBSBDDSSSSSB ', '                     ',)
    .aisle('  BSSSSSSBSBSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSBSBSSSSSSB  ', '                     ',)
    .aisle('   BSSSSSBSBSSSSSB   ', '                     ',)
    .aisle('    BBSSSBSBSSSBB    ', '                     ',)
    .aisle('      BBSBSBSBB      ', '          L          ',)
    .aisle('        BBBBB        ', '          G          ',)
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:cracked_deepslate_tiles')))
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:deepslate_bricks')))
    .where('D', $BlockInWorld.hasState((state) => state.is('minecraft:polished_deepslate_stairs')))
    .where('A', $BlockInWorld.hasState((state) => state.is('graveyard:ossuary')))
    .where('C', $BlockInWorld.hasState((state) => state.is('graveyard:dark_iron_block')))
    .where('G', $BlockInWorld.hasState((state) => state.is('graveyard:deepslate_gravestone')))
    .where('L', $BlockInWorld.hasState((state) => state.is('graveyard:leaning_skeleton')))
    .where('O', $BlockInWorld.hasState((state) => state.is('minecraft:candle')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .build()

const GraveyardBasicArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle(' BSSSSSSSBSBSSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSBBBBBSSSSSSB ', '                     ',)
    .aisle('BSSSSSSBBDDDBBSSSSSSB', '        O   O        ',)
    .aisle('BSSSSSBBDDADDBBSSSSSB', '                     ',)
    .aisle('BSSSSSSBDACADBSSSSSSB', '          @          ',)
    .aisle('BSSSSSBBDDADDBBSSSSSB', '                     ',)
    .aisle('BSSSSSSBBDDDBBSSSSSSB', '        O   O        ',)
    .aisle(' BSSSSSSBBBBBSSSSSSB ', '                     ',)
    .aisle(' BSSSSSSSBSBSSSSSSSB ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:cracked_deepslate_tiles')))
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:deepslate_bricks')))
    .where('D', $BlockInWorld.hasState((state) => state.is('minecraft:polished_deepslate_stairs')))
    .where('A', $BlockInWorld.hasState((state) => state.is('minecraft:bone_block')))
    .where('C', $BlockInWorld.hasState((state) => state.is('graveyard:dark_iron_block')))
    .where('O', $BlockInWorld.hasState((state) => state.is('minecraft:candle')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .build()