// priority: 2000
const NetherAdvanceArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBNNLNNBB      ', '                     ',)
    .aisle('    BBSSSNLNSSSBB    ', '                     ',)
    .aisle('   BSSSSSNLNSSSSSB   ', '                     ',)
    .aisle('  BSSSSSSNLNSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSNLNSSSSSSB  ', '                     ',)
    .aisle(' BSSSSSSNNLNNSSSSSSB ', '                     ',)
    .aisle(' BSSSSSGLLLLLGSSSSSB ', '                     ',)
    .aisle('BNSSSSNLDCCCDLNSSSSNB', '        @   @        ',)
    .aisle('BNNNNNNLCTTTCLNNNNNNB', '                     ',)
    .aisle('BLLLLLLLCTQTCLLLLLLLB', '                     ',)
    .aisle('BNNNNNNLCTTTCLNNNNNNB', '                     ',)
    .aisle('BNSSSSNLDCCCDLNSSSSNB', '        @   @        ',)
    .aisle(' BSSSSSGLLLLLGSSSSSB ', '                     ',)
    .aisle(' BSSSSSSNNLNNSSSSSSB ', '                     ',)
    .aisle('  BSSSSSSNLNSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSNLNSSSSSSB  ', '                     ',)
    .aisle('   BSSSSSNLNSSSSSB   ', '                     ',)
    .aisle('    BBSSSNLNSSSBB    ', '                     ',)
    .aisle('      BBNNLNNBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:chiseled_polished_blackstone')))
    .where('N', $BlockInWorld.hasState((state) => state.is('minecraft:nether_bricks')))
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:polished_blackstone_bricks')))
    .where('L', $BlockInWorld.hasState((state) => state.is('minecraft:magma_block')))
    .where('D', $BlockInWorld.hasState((state) => state.is('minecraft:ancient_debris')))
    .where('G', $BlockInWorld.hasState((state) => state.is('minecraft:gold_block')))
    .where('C', $BlockInWorld.hasState((state) => state.is('minecraft:crying_obsidian')))
    .where('Q', $BlockInWorld.hasState((state) => state.is('minecraft:respawn_anchor')))
    .where('T', $BlockInWorld.hasState((state) => state.is('cataclysm:obsidian_brick_stairs')))
    .where('@', $BlockInWorld.hasState((state) => state.is('minecraft:soul_lantern')))
    .build()

const NetherBasicArenaPattern = $BlockPatternBuilder.start()
    .aisle('        BBBBB        ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSSLSSSSSSSB  ', '                     ',)
    .aisle(' BSSSSSSNNLNNSSSSSSB ', '                     ',)
    .aisle(' BSSSSSGLLLLLGSSSSSB ', '                     ',)
    .aisle('BSSSSSNLDCCCDLNSSSSSB', '                     ',)
    .aisle('BSSSSSNLCTTTCLNSSSSSB', '                     ',)
    .aisle('BSSSSLLLCTQTCLLLSSSSB', '                     ',)
    .aisle('BSSSSSNLCTTTCLNSSSSSB', '                     ',)
    .aisle('BSSSSSNLDCCCDLNSSSSSB', '                     ',)
    .aisle(' BSSSSSGLLLLLGSSSSSB ', '                     ',)
    .aisle(' BSSSSSSNNLNNSSSSSSB ', '                     ',)
    .aisle('  BSSSSSSSLSSSSSSSB  ', '                     ',)
    .aisle('  BSSSSSSSSSSSSSSSB  ', '                     ',)
    .aisle('   BSSSSSSSSSSSSSB   ', '                     ',)
    .aisle('    BBSSSSSSSSSBB    ', '                     ',)
    .aisle('      BBSSSSSBB      ', '                     ',)
    .aisle('        BBBBB        ', '                     ',)
    .where('B', $BlockInWorld.hasState((state) => state.is('minecraft:chiseled_polished_blackstone')))
    .where('N', $BlockInWorld.hasState((state) => state.is('minecraft:nether_bricks')))
    .where('S', $BlockInWorld.hasState((state) => state.is('minecraft:polished_blackstone_bricks')))
    .where('L', $BlockInWorld.hasState((state) => state.is('minecraft:magma_block')))
    .where('D', $BlockInWorld.hasState((state) => state.is('minecraft:nether_quartz_ore')))
    .where('G', $BlockInWorld.hasState((state) => state.is('minecraft:gold_block')))
    .where('C', $BlockInWorld.hasState((state) => state.is('minecraft:obsidian')))
    .where('Q', $BlockInWorld.hasState((state) => state.is('minecraft:respawn_anchor')))
    .where('T', $BlockInWorld.hasState((state) => state.is('cataclysm:obsidian_brick_stairs')))
    .build()