// priority: 500
StartupEvents.registry('item', event => {
    event.create('kubejs:sea_bunny_skin').maxStackSize(1).texture('kubejs:item/organs/nature/sea_bunny_skin').tag('kubejs:nature')
    event.create('kubejs:mammary_gland').maxStackSize(1).texture('kubejs:item/organs/nature/mammary_gland').tag('kubejs:nature')
    event.create('kubejs:moew_nose').maxStackSize(1).texture('kubejs:item/organs/nature/moew_nose').tag('kubejs:nature')
    event.create('kubejs:leaf_insect_exoskeleton').maxStackSize(1).texture('kubejs:item/organs/nature/leaf_insect_exoskeleton').tag('kubejs:nature')
    event.create('kubejs:tentacles_harvester').maxStackSize(1).texture('kubejs:item/organs/nature/tentacles_harvester').tag('kubejs:nature')
    event.create('kubejs:dumbo_octopus_hat').maxStackSize(1).texture('kubejs:item/organs/nature/dumbo_octopus_hat').tag('kubejs:nature')
    event.create('kubejs:ferret_tail').maxStackSize(1).texture('kubejs:item/organs/nature/ferret_tail').tag('kubejs:nature')
    event.create('kubejs:jumping_spider_leg').maxStackSize(1).texture('kubejs:item/organs/nature/jumping_spider_leg').tag('kubejs:nature')
    event.create('kubejs:koi_fish_scale').maxStackSize(1).texture('kubejs:item/organs/nature/koi_fish_scale').tag('kubejs:nature')
    event.create('kubejs:otter_tooth').maxStackSize(1).texture('kubejs:item/organs/nature/otter_tooth').tag('kubejs:nature')
    event.create('kubejs:red_panda_tail').maxStackSize(1).texture('kubejs:item/organs/nature/red_panda_tail').tag('kubejs:nature')
    event.create('kubejs:shima_enaga_feather').maxStackSize(1).texture('kubejs:item/organs/nature/shima_enaga_feather').tag('kubejs:nature')
    event.create('kubejs:deer_horn').maxStackSize(1).texture('kubejs:item/organs/nature/deer_horn').tag('kubejs:nature')
    event.create('kubejs:red_wolf_beard').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/nature/red_wolf_beard').tag('kubejs:nature')
    event.create('kubejs:raccoon_paw').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/nature/raccoon_paw').tag('kubejs:nature')
    event.create('kubejs:boar_nose').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/nature/boar_nose').tag('kubejs:nature')
    event.create('kubejs:minisheep_gland').maxStackSize(1).texture('kubejs:item/organs/nature/minisheep_gland').tag('kubejs:nature')
    event.create('kubejs:squirrel_tail').maxStackSize(1).texture('kubejs:item/organs/nature/squirrel_tail').tag('kubejs:nature')
    event.create('kubejs:pelican_larynx').maxStackSize(1).texture('kubejs:item/organs/nature/pelican_larynx').tag('kubejs:nature')
    event.create('kubejs:owl_vertebrae').maxStackSize(1).texture('kubejs:item/organs/nature/owl_vertebrae').tag('kubejs:nature')
    event.create('kubejs:bison_horn').maxStackSize(1).texture('kubejs:item/organs/nature/bison_horn').tag('kubejs:nature')
    event.create('kubejs:turkey_gizzard').maxStackSize(1).texture('kubejs:item/organs/nature/turkey_gizzard').tag('kubejs:nature').tag('kubejs:stomach')
    event.create('kubejs:penguin_flipper').maxStackSize(1).texture('kubejs:item/organs/nature/penguin_flipper').tag('kubejs:nature')
    event.create('kubejs:dog_tail').maxStackSize(1).texture('kubejs:item/organs/nature/dog_tail').tag('kubejs:nature')
    event.create('kubejs:hedgehog_thorn').maxStackSize(1).texture('kubejs:item/organs/nature/hedgehog_thorn').tag('kubejs:nature')
    event.create('kubejs:cassowary_muscle').maxStackSize(1).texture('kubejs:item/organs/nature/cassowary_muscle').tag('kubejs:nature').tag('kubejs:muscle')
    event.create('kubejs:flamingo_beak').maxStackSize(1).texture('kubejs:item/organs/nature/flamingo_beak').tag('kubejs:nature')
    event.create('kubejs:urchinkin_stinger').maxStackSize(1).tag('kubejs:nature').texture('kubejs:item/organs/nature/urchinkin_stinger')
})

