// priority: 500
StartupEvents.registry('item', event => {
    event.create('kubejs:sea_bunny_skin').maxStackSize(1).texture('kubejs:item/organs/nature/sea_bunny_skin').tag('kubejs:nature')
    event.create('kubejs:mammary_gland').maxStackSize(1).texture('kubejs:item/organs/nature/mammary_gland').tag('kubejs:nature')
    event.create('kubejs:moew_nose').maxStackSize(1).texture('kubejs:item/organs/nature/moew_nose').tag('kubejs:nature')
    event.create('kubejs:leaf_insect_exoskeleton').maxStackSize(1).texture('kubejs:item/organs/nature/leaf_insect_exoskeleton').tag('kubejs:nature')
    event.create('kubejs:tentacles_harvester').maxStackSize(1).texture('kubejs:item/organs/nature/tentacles_harvester').tag('kubejs:nature')
    event.create('kubejs:dumbo_octopus_hat').maxStackSize(1).texture('kubejs:item/organs/nature/dumbo_octopus_hat').tag('kubejs:nature')
    event.create('kubejs:ferret_tail').maxStackSize(1).texture('kubejs:item/organs/nature/ferret_tail').tag('kubejs:nature')
    event.create('kubejs:jumping_spider_leg').maxStackSize(1).texture('kubejs:item/organs/nature/jumping_spider_leg').tag('kubejs:nature')
    event.create('kubejs:koi_fish_scale').maxStackSize(1).texture('kubejs:item/organs/nature/koi_fish_scale').tag('kubejs:nature')
    event.create('kubejs:otter_tooth').maxStackSize(1).texture('kubejs:item/organs/nature/otter_tooth').tag('kubejs:nature')
    event.create('kubejs:red_panda_tail').maxStackSize(1).texture('kubejs:item/organs/nature/red_panda_tail').tag('kubejs:nature')
    event.create('kubejs:shima_enaga_feather').maxStackSize(1).texture('kubejs:item/organs/nature/shima_enaga_feather').tag('kubejs:nature')
    event.create('kubejs:deer_horn').maxStackSize(1).texture('kubejs:item/organs/nature/deer_horn').tag('kubejs:nature')
    event.create('kubejs:red_wolf_beard').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/nature/red_wolf_beard').tag('kubejs:nature')
    event.create('kubejs:raccoon_paw').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/nature/raccoon_paw').tag('kubejs:nature')
})