// priority: 500
StartupEvents.registry('item', event => {
    event.create('kubejs:demon_eyeball').maxStackSize(1).texture('kubejs:item/organs/relic/demon_eyeball').tag('kubejs:relic')
    event.create('kubejs:immortal_volcanic_rock').maxStackSize(1).texture('kubejs:item/organs/relic/immortal_volcanic_rock').tag('kubejs:relic').tag('kubejs:nether')
    event.create('kubejs:frenzy_blast_furance').maxStackSize(1).texture('kubejs:item/organs/relic/frenzy_blast_furance').tag('kubejs:relic')
    event.create('kubejs:warden_core').maxStackSize(1).texture('kubejs:item/organs/relic/warden_core').tag('kubejs:relic')
    event.create('kubejs:netherite_muscle').maxStackSize(1).texture('kubejs:item/organs/relic/netherite_muscle').tag('kubejs:relic').tag('kubejs:nether').tag('kubejs:muscle')
    event.create('kubejs:ender_guardian_spine').maxDamage(10).maxStackSize(1).texture('kubejs:item/organs/relic/ender_guardian_spine').tag('kubejs:relic').tag('kubejs:ender').tag('kubejs:spine')
    event.create('kubejs:harbinger_lung').maxDamage(30).maxStackSize(1).texture('kubejs:item/organs/relic/harbinger_lung').tag('kubejs:relic').tag('kubejs:lung').tag('kubejs:machine')
    event.create('kubejs:leviathan_rib').maxStackSize(1).texture('kubejs:item/organs/relic/leviathan_rib').tag('kubejs:relic').tag('kubejs:bone').tag('kubejs:magic')
    event.create('kubejs:remnant_heart').maxStackSize(1).texture('kubejs:item/organs/relic/remnant_heart').tag('kubejs:heart').tag('kubejs:relic').tag('kubejs:magic')
    event.create('kubejs:maledictus_wing').maxStackSize(1).texture('kubejs:item/organs/relic/maledictus_wing').tag('kubejs:relic').tag('kubejs:magic')
    event.create('kubejs:scylla_star_gem').maxStackSize(1).tag('kubejs:relic').tag('kubejs:magic').texture('kubejs:item/organs/relic/scylla_star_gem').tag('kubejs:gem')
    event.create('kubejs:dying_heart').maxStackSize(1).tag('kubejs:relic').tag('kubejs:magic').texture('kubejs:item/organs/relic/dying_heart')
})
