// priority: 2000
const $CompoundTag = Java.loadClass('net.minecraft.nbt.CompoundTag')
const $ListTag = Java.loadClass('net.minecraft.nbt.ListTag')
const $StructurePlaceSettings = Java.loadClass('net.minecraft.world.level.levelgen.structure.templatesystem.StructurePlaceSettings')
const $Mirror = Java.loadClass('net.minecraft.world.level.block.Mirror')
const $Rotation = Java.loadClass('net.minecraft.world.level.block.Rotation')
const $ChunkStatus = Java.loadClass('net.minecraft.world.level.chunk.ChunkStatus')
const $PalettedContainer = Java.loadClass('net.minecraft.world.level.chunk.PalettedContainer')
const $StructureMode = Java.loadClass('net.minecraft.world.level.block.state.properties.StructureMode')

const $Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const $ResourceKey = Java.loadClass('net.minecraft.resources.ResourceKey')
const $Float = Java.loadClass('java.lang.Float')
const $ChestCavityUtil = Java.loadClass('net.tigereye.chestcavity.util.ChestCavityUtil')
const $AttributeModifier = Java.loadClass('net.minecraft.world.entity.ai.attributes.AttributeModifier')

const $Operation = Java.loadClass('net.minecraft.world.entity.ai.attributes.AttributeModifier$Operation')

const $DamageTypes = Java.loadClass('net.minecraft.world.damagesource.DamageTypes')
const $DamageSources = Java.loadClass('net.minecraft.world.damagesource.DamageSources')
const $DefaultLunarEvents = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.DefaultLunarEvents')
const $LunarEvent = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.LunarEvent')
const $ImmutableMap = Java.loadClass('com.google.common.collect.ImmutableMap')
const $LunarEventClientSettings = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.client.LunarEventClientSettings')
const $ColorSettings = Java.loadClass('corgitaco.enhancedcelestials.api.client.ColorSettings')
const $LunarTextComponents = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.LunarTextComponents')
const $CustomTranslationTextComponent = Java.loadClass('corgitaco.enhancedcelestials.util.CustomTranslationTextComponent')
const $LunarMobSettings = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.LunarMobSettings')
const $LunarMobSpawnInfo = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.LunarMobSpawnInfo')
const $MobSpawnSettings = Java.loadClass('net.minecraft.world.level.biome.MobSpawnSettings')
const $FlipCondition = Java.loadClass('corgitaco.corgilib.entity.condition.FlipCondition')
const $AnyCondition = Java.loadClass('corgitaco.corgilib.entity.condition.AnyCondition')
const $DropSettings = Java.loadClass('corgitaco.enhancedcelestials.api.lunarevent.DropSettings')