StartupEvents.registry('block', event => {
    event.create('kubejs:orichalcum_block')
          .material('metal')
          .hardness(5.0)
          .resistance(6.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/orichalcum_block')
          
    event.create('kubejs:potion_gold_block')
          .material('metal')
          .hardness(4.0)
          .resistance(5.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/potion_gold_block')
      
    event.create('kubejs:glintstone_block')
          .material('metal')
          .hardness(2.0)
          .resistance(4.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/glintstone_block')  
    
    event.create('kubejs:carian_steel_block')
          .material('metal')
          .hardness(3.0)
          .resistance(4.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/carian_steel_block')
          
    event.create('kubejs:fire_block')
          .material('metal')
          .hardness(3.0)
          .resistance(4.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/fire_block')
          
    event.create('kubejs:dark_block')
          .material('metal')
          .hardness(3.0)
          .resistance(4.0)
          .tagBlock('mineable/pickaxe')
          .requiresTool(true)
          .textureAll('kubejs:block/dark_block')     
})