// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_heart')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.dragon_blood_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.dragon_blood_heart.alt.2', FrozenHover))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_lung')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_lung.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_muscle.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_rib')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_rib.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_liver')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_liver.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_kidney.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_spine')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_spine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_intestine.default.1').gray())
)
RegistryOrganTooltip(new MultiStateTooltip('kubejs:dragon_blood_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.dragon_blood_stomach.default.1').gray())
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_golem_line')
    .addDefault(Text.translatable('tooltips.kubejs.ender_golem_line.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ender_golem_line.alt.1', KeyActiveHover, Text.gold('10')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:endermaptera_shell')
    .addDefault(Text.translatable('tooltips.kubejs.endermaptera_shell.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.endermaptera_shell.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_breath')
    .addDefault(Text.translatable('tooltips.kubejs.ender_breath.default.1').gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_ectoplasm')
    .addDefault(Text.translatable('tooltips.kubejs.ender_ectoplasm.default.1').gray())
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:ender_eye')
    .addDefault(Text.translatable('tooltips.kubejs.ender_eye.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ender_eye.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:endermite_gland')
    .addDefault(Text.translatable('tooltips.kubejs.endermite_gland.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.endermite_gland.alt.1'))
)