// priority: 900
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:villager_own_you')
    .addDefault(Text.translatable('tooltips.kubejs.villager_own_you.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.villager_own_you.alt.1'))
)
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:god_tinker_heart')
    .addDefault(Text.translatable('tooltips.kubejs.god_tinker_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.god_tinker_heart.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.god_tinker_heart.alt.2', 3))
)
