// priority: 900
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:furnace_core')
    .addDefault(Text.translatable('tooltips.kubejs.furnace_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.1', Text.gold('300')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.2', Text.gold('2'), Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.furnace_core.alt.3'))
    .addCtrl(EternalFlameSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.furnace_core.ctrl.2'))
    .addMPMType(OrganItemMPMTypeNotShow, OrganItemMPMTypeNotShowText)
    .addMPMType(OrganItemMPMTypeShow, OrganItemMPMTypeShowText)
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:burning_heart')
    .addDefault(Text.translatable('tooltips.kubejs.burning_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.1', Text.gold('5')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.2', Text.gold('100%')))
    .addAlt(Text.translatable('tooltips.kubejs.burning_heart.alt.3'))
    .addCtrl(EternalFlameSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.burning_heart.ctrl.1'))
    .addMPMType(OrganItemMPMTypeNotShow, OrganItemMPMTypeNotShowText)
    .addMPMType(OrganItemMPMTypeShow, OrganItemMPMTypeShowText)
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:energy_bottle_red')
    .addDefault(Text.translatable('tooltips.kubejs.energy_bottle_red.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.1', Text.gold('100')))
    .addAlt(Text.translatable('tooltips.kubejs.energy_bottle_red.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.1', Text.gold('300%')))
    .addCtrl(EternalFlameSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.energy_bottle_red.ctrl.2', Text.gold('200%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:revolution_cable')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_cable.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_cable.ctrl.1', Text.gold('300%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:revolution_cable')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_cable.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_cable.alt.2', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_cable.ctrl.1', Text.gold('300%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:revolution_relay')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_relay.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_relay.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_relay.ctrl.1', Text.gold('300%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:revolution_delay')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_delay.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_delay.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.revolution_delay.ctrl.1', Text.gold('300%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:revolution_bell')
    .addDefault(Text.translatable('tooltips.kubejs.revolution_bell.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.revolution_bell.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.revolution_bell.alt.2'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:blaze_pressurizer')
    .addDefault(Text.translatable('tooltips.kubejs.blaze_pressurizer.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.1', Text.gold('3')))
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.blaze_pressurizer.alt.3'))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.blaze_pressurizer.ctrl.1', Text.gold('300%')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:telescopic_arm')
    .addDefault(Text.translatable('tooltips.kubejs.telescopic_arm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.telescopic_arm.alt.1', Text.gold('1')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.telescopic_arm.ctrl.1', Text.gold('4')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:telescopic_attack_arm')
    .addDefault(Text.translatable('tooltips.kubejs.telescopic_attack_arm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.telescopic_attack_arm.alt.1', Text.gold('0.5')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.telescopic_attack_arm.ctrl.1', Text.gold('2')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:lava_life_cycle_system')
    .addDefault(Text.translatable('tooltips.kubejs.lava_life_cycle_system.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.lava_life_cycle_system.alt.3', Text.gold('10')))
    .addCtrl(MachinaryLubricantSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.lava_life_cycle_system.cltr.1', Text.gold('40')))
)