// priority: 900
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:originiums')
    .addDefault(Text.translatable('tooltips.kubejs.originiums.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.originiums.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.originiums.alt.2', Text.gold('10'), Text.gold('3')))
    .addAlt(Text.translatable('tooltips.kubejs.originiums.alt.3'))
    .addMPMType(OrganItemMPMTypeNotShow, OrganItemMPMTypeNotShowText)
    .addMPMType(OrganItemMPMTypeShow, OrganItemMPMTypeShowText)
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:harvest_star_gem')
    .addDefault(Text.translatable('tooltips.kubejs.harvest_star_gem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.harvest_star_gem.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.harvest_star_gem.alt.2'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:heal_star_gem')
    .addDefault(Text.translatable('tooltips.kubejs.heal_star_gem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.heal_star_gem.alt.1'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:coral_armor')
    .addDefault(Text.translatable('tooltips.kubejs.coral_armor.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.coral_armor.alt.1'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:deepling_star_gem')
    .addDefault(Text.translatable('tooltips.kubejs.deepling_star_gem.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.deepling_star_gem.alt.1', Text.gold('20'), FrozenHover))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:animted_soul')
    .addDefault(Text.translatable('tooltips.kubejs.animted_soul.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.animted_soul.alt.1', Text.gold('10'), Text.gold('1/2')))
    .addAlt(Text.translatable('tooltips.kubejs.animted_soul.alt.2', Text.gold('60')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:amethyst_core')
    .addDefault(Text.translatable('tooltips.kubejs.amethyst_core.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.amethyst_core.alt.1', Text.gold('1/10')))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:deepling_ectoplasm')
    .addDefault(Text.translatable('tooltips.kubejs.deepling_ectoplasm.default.1').gray())
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:koboleton_spine')
    .addDefault(Text.translatable('tooltips.kubejs.koboleton_spine.default.1').gray())
)
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:koboleton_rib')
    .addDefault(Text.translatable('tooltips.kubejs.koboleton_rib.default.1').gray())
)
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:koboleton_coccyx')
    .addDefault(Text.translatable('tooltips.kubejs.koboleton_coccyx.default.1').gray())
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:aptrgangr_soul')
    .addDefault(Text.translatable('tooltips.kubejs.aptrgangr_soul.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.aptrgangr_soul.alt.1', SoildCoreHover))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:draugr_skull')
    .addDefault(Text.translatable('tooltips.kubejs.draugr_skull.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.draugr_skull.alt.1', FrozenHover, Text.gold('10')))
)
