// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:ignited_armour')
    .addDefault(Text.translatable('tooltips.kubejs.ignited_armour.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.ignited_armour.alt.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:embers_liver')
    .addDefault(Text.translatable('tooltips.kubejs.embers_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.embers_liver.alt.1'))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.embers_liver.ctrl.1'))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:blaze_spine')
    .addDefault(Text.translatable('tooltips.kubejs.blaze_spine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.blaze_spine.alt.1', Text.gold('1')))
    .addAlt(Text.translatable('tooltips.kubejs.blaze_spine.alt.2', Text.gold('3')))
    .addCtrl(RevolutionFlameType)
    .addCtrl(Text.translatable('tooltips.kubejs.blaze_spine.ctrl.1'))
)
