// priority: 900
RegisteryOrganTooltip(new MultiStateTooltip('kubejs:cherry_bone')
    .addDefault(Text.translatable('tooltips.kubejs.cherry_bone.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.cherry_bone.alt.1'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:crimson_brain')
    .addDefault(Text.translatable('tooltips.kubejs.crimson_brain.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.crimson_brain.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.crimson_brain.alt.2'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:hop_kidney')
    .addDefault(Text.translatable('tooltips.kubejs.hop_kidney.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.hop_kidney.alt.1'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:lily_pad_lung')
    .addDefault(Text.translatable('tooltips.kubejs.lily_pad_lung.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.lily_pad_lung.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.lily_pad_lung.alt.2'))
)


RegisteryOrganTooltip(new MultiStateTooltip('kubejs:pitcher_stomach')
    .addDefault(Text.translatable('tooltips.kubejs.pitcher_stomach.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.pitcher_stomach.alt.3'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:twisting_weeping_intestine')
    .addDefault(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.twisting_weeping_intestine.alt.3'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:vita_berry')
    .addDefault(Text.translatable('tooltips.kubejs.vita_berry.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_berry.alt.1'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:vita_rose_liver')
    .addDefault(Text.translatable('tooltips.kubejs.vita_rose_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_rose_liver.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.vita_rose_liver.alt.2'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:vita_sunflower')
    .addDefault(Text.translatable('tooltips.kubejs.vita_sunflower.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.vita_sunflower.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.vita_sunflower.alt.2'))
)

RegisteryOrganTooltip(new MultiStateTooltip('kubejs:rootling_ectoplasm')
    .addDefault(Text.translatable('tooltips.kubejs.rootling_ectoplasm.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rootling_ectoplasm.alt.1', Text.gold('9 * 9')))
    .addAlt(Text.translatable('tooltips.kubejs.rootling_ectoplasm.alt.2', Text.gold('5')))
)
