// priority: 900
RegistryOrganTooltip(new MultiStateTooltip('kubejs:rose_quartz_muscle')
    .addDefault(Text.translatable('tooltips.kubejs.rose_quartz_muscle.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_muscle.alt.1', Text.gold('1'), Text.gold('1')))
    .addCtrl(RosyExplosionSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_muscle.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_muscle.ctrl.2', Text.gold('1'), Text.gold('1')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rose_quartz_heart')
    .addDefault(Text.translatable('tooltips.kubejs.rose_quartz_heart.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_heart.alt.1', Text.gold('1'), Text.gold('0.5')))
    .addCtrl(RosyExplosionSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_heart.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_heart.ctrl.2', Text.gold('1'), Text.gold('0.5')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rose_quartz_rib')
    .addDefault(Text.translatable('tooltips.kubejs.rose_quartz_rib.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_rib.alt.1', Text.gold('1'), Text.gold('0.1')))
    .addCtrl(RosyExplosionSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_rib.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_rib.ctrl.2', Text.gold('1'), Text.gold('0.1')))
)


RegistryOrganTooltip(new MultiStateTooltip('kubejs:rose_quartz_dialyzer')
    .addDefault(Text.translatable('tooltips.kubejs.rose_quartz_dialyzer.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_dialyzer.alt.1', KeyActiveHover))
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_dialyzer.alt.2', Text.gold('1'), Text.gold('3')))
    .addCtrl(RosyExplosionSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_dialyzer.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_dialyzer.ctrl.2', Text.gold('1'), Text.gold('1')))
)

RegistryOrganTooltip(new MultiStateTooltip('kubejs:rose_quartz_liver')
    .addDefault(Text.translatable('tooltips.kubejs.rose_quartz_liver.default.1').gray())
    .addAlt(Text.translatable('tooltips.kubejs.rose_quartz_liver.alt.1', Text.gold('1'), Text.gold('0.5')))
    .addCtrl(RosyExplosionSlotType)
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_liver.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.rose_quartz_liver.ctrl.2', Text.gold('1'), Text.gold('0.5')))
)