// priority: 1000
StartupEvents.registry('minecraft:item', event => {
    event.create('kubejs:dark_witness_memory', 'basic')
        .texture('kubejs:item/curios/dark_witness_memory')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
            .canUnequip(() => true)
            .dynamicAttribute(ctx => {
                const item = ctx.getStack()
                const nbt = item.getOrCreateTag()
                ctx.modify('minecraft:generic.armor', 'DarkWitnessMemoryArmorAddition', RoundFix(nbt.getFloat('armor'), 2), 'addition')
            })
        )
        .tag('curios:memory')

    event.create('kubejs:reunion_memory', 'basic')
        .texture('kubejs:item/curios/reunion_memory')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
            .canUnequip(() => true)
            .dynamicAttribute(ctx => {
                const item = ctx.getStack()
                const nbt = item.getOrCreateTag()
                ctx.modify('tconstruct:player.experience_multiplier', 'ReunionMemoryExperienceMultiplier', RoundFix(nbt.getFloat('experienceMultiplier'), 2), 'addition')
            })
        )
        .tag('curios:memory')

    event.create('kubejs:fear_memory', 'basic')
        .texture('kubejs:item/curios/fear_memory')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
            .canUnequip(() => true)
            .dynamicAttribute(ctx => {
                const item = ctx.getStack()
                const nbt = item.getOrCreateTag()
                ctx.modify('attributeslib:crit_damage', 'FearMemoryCritDamageAddition', RoundFix(nbt.getFloat('critDamage'), 2), 'addition')
            })
        )
        .tag('curios:memory')

    event.create('kubejs:cheat_death_memory', 'basic')
        .texture('kubejs:item/curios/cheat_death_memory')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
            .canUnequip(() => true)
            .dynamicAttribute(ctx => {
                const item = ctx.getStack()
                const nbt = item.getOrCreateTag()
                ctx.modify('minecraft:generic.luck', 'CheatDeathMemoryLuckAddition', RoundFix(nbt.getFloat('luck'), 2), 'addition')
            })
        )
        .tag('curios:memory')

    event.create('kubejs:eternal_miracle', 'basic')
        .texture('kubejs:item/curios/fear_memory')
        .maxStackSize(1)
        .attachCapability(CuriosCapabilityBuilder.CURIOS.itemStack()
            .canEquip(() => true)
            .canUnequip(() => true)
            .dynamicAttribute(ctx => {
                const item = ctx.getStack()
                const nbt = item.getOrCreateTag()
                ctx.modify('minecraft:generic.attack_damage', 'EternalMiracleAttackDamageAddition', RoundFix(nbt.getFloat('attackDamage'), 2), 'addition')
            })
        )
        .tag('curios:miracle')
    // todo 永恒祭坛最终目标、唯一饰品、无限成长、收集类、后续简化配方、能够提供任务线流程
})