// priority: 800
ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:counterweight_gear')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.counterweight_gear.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.counterweight_gear.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:oracle_gate')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.oracle_gate.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.oracle_gate.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:simulated_unit')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.simulated_unit.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.simulated_unit.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:redstone_capacitor')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.redstone_capacitor.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.redstone_capacitor.shift.1'))
)


ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:random_tick_spring')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.random_tick_spring.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.random_tick_spring.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:structural_bolt')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.structural_bolt.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.structural_bolt.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:unstable_matter')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.unstable_matter.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.unstable_matter.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:refined_brass_ingot')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.refined_brass_ingot.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.refined_brass_ingot.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:reverse_causality_chip')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.reverse_causality_chip.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.reverse_causality_chip.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:timing_valve')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.timing_valve.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.timing_valve.shift.1', UnstableHover))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:stable_substrate')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.stable_substrate.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.stable_substrate.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:amethyst_resonator')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.amethyst_resonator.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.amethyst_resonator.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:mantle_ore')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.mantle_ore.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.mantle_ore.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:world_computer')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.world_computer.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.world_computer.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:eternal_altar')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.eternal_altar.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.eternal_altar.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:growth_vat')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.growth_vat.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.growth_vat.shift.1'))
)