// priority: 500
RegistryOrgan('kubejs:rotten_appendix').addScore('chestcavity:luck', 0.5)
RegistryOrgan('kubejs:rotten_intestine').addScore('chestcavity:nutrition', 0.75)
RegistryOrgan('kubejs:rotten_heart').addScore('chestcavity:health', 0.75)
RegistryOrgan('kubejs:rotten_kidney').addScore('chestcavity:filtration', 0.75)
RegistryOrgan('kubejs:rotten_liver').addScore('chestcavity:detoxification', 0.75)
RegistryOrgan('kubejs:rotten_lung').addScore('chestcavity:breath_recovery', 0.75).addScore('chestcavity:breath_capacity', 0.75).addScore('chestcavity:endurance', 0.75)
RegistryOrgan('kubejs:rotten_muscle').addScore('chestcavity:strength', 1.5).addScore('chestcavity:speed', -0.25)
RegistryOrgan('kubejs:rotten_rib').addScore('chestcavity:defense', 0.75)
RegistryOrgan('kubejs:rotten_spine').addScore('chestcavity:nerves', 0.75).addScore('chestcavity:speed', -0.25)
RegistryOrgan('kubejs:rotten_spleen').addScore('chestcavity:metabolism', 0.75)
RegistryOrgan('kubejs:rotten_stomach').addScore('chestcavity:digestion', 0.75)
