// priority: 5000
const $CompoundTag = Java.loadClass('net.minecraft.nbt.CompoundTag')
const $ListTag = Java.loadClass('net.minecraft.nbt.ListTag')
const $BlockEntity = Java.loadClass('net.minecraft.world.level.block.entity.BlockEntity')
const $Registries = Java.loadClass('net.minecraft.core.registries.Registries')
const $TagKey = Java.loadClass('net.minecraft.tags.TagKey')
const $EyeofEnder = Java.loadClass('net.minecraft.world.entity.projectile.EyeOfEnder')
const $ClipContext = Java.loadClass('net.minecraft.world.level.ClipContext')
const $ClipContextBlock = Java.loadClass('net.minecraft.world.level.ClipContext$Block')
const $ClipContextFluid = Java.loadClass('net.minecraft.world.level.ClipContext$Fluid')

const $RangedAttribute = Java.loadClass('net.minecraft.world.entity.ai.attributes.RangedAttribute')
const $EntityType = Java.loadClass('net.minecraft.world.entity.EntityType')
const $ServerPlayer = Java.loadClass('net.minecraft.server.level.ServerPlayer')
const $LivingEntity = Java.loadClass('net.minecraft.world.entity.LivingEntity')
const $CommonUtil = Java.loadClass('net.tigereye.chestcavity.util.CommonUtil')
const $IntegerProperty = Java.loadClass('net.minecraft.world.level.block.state.properties.IntegerProperty')
const $Integer = Java.loadClass('java.lang.Integer')
const $MobEffectInstance = Java.loadClass('net.minecraft.world.effect.MobEffectInstance')
const $MobSpawnType = Java.loadClass('net.minecraft.world.entity.MobSpawnType')
const $PathfinderMob = Java.loadClass('net.minecraft.world.entity.PathfinderMob')

const $FireBomb = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.magma_ball.FireBomb')
const $AbstractSpell = Java.loadClass('io.redspace.ironsspellbooks.api.spells.AbstractSpell')

const $InteractionHand = Java.loadClass('net.minecraft.world.InteractionHand')

const $SummonedZombie = Java.loadClass('io.redspace.ironsspellbooks.entity.mobs.SummonedZombie')
const $SummonedSkeleton = Java.loadClass('io.redspace.ironsspellbooks.entity.mobs.SummonedSkeleton')
const $ISSUtils = Java.loadClass('io.redspace.ironsspellbooks.api.util.Utils')
const $ExtendedEvokerFang = Java.loadClass('io.redspace.ironsspellbooks.entity.spells.ExtendedEvokerFang')

const $AltarBlockEntity = Java.loadClass('net.jrdemiurge.skyarena.block.entity.AltarBlockEntity')
const $LootContextParams = Java.loadClass('net.minecraft.world.level.storage.loot.parameters.LootContextParams')
const $Serializer = Java.loadClass('net.minecraft.network.chat.Component$Serializer')
const $ItemEntity = Java.loadClass('net.minecraft.world.entity.item.ItemEntity')
const $ToolStats = Java.loadClass('slimeknights.tconstruct.library.tools.stat.ToolStats')
const $ToolStatId = Java.loadClass('slimeknights.tconstruct.library.tools.stat.ToolStatId')