// priority: 998
const IsLoadedKubeloader = Platform.isLoaded('kubeloader')

if (IsLoadedKubeloader) {
    ContentPacks.putShared('RegistryOrganTooltip', RegistryOrganTooltip)
    ContentPacks.putShared('ApplyMultiStateTooltip', ApplyMultiStateTooltip)
    ContentPacks.putShared('MultiStateTooltip', MultiStateTooltip)

    ContentPacks.putShared('DefaultSlotType', DefaultSlotType)
    ContentPacks.putShared('HighAdaptabilitySlotType', HighAdaptabilitySlotType)
    ContentPacks.putShared('RosyExplosionSlotType', RosyExplosionSlotType)
    ContentPacks.putShared('RevolutionFlameType', RevolutionFlameType)
    ContentPacks.putShared('MachinaryLubricantSlotType', MachinaryLubricantSlotType)
    ContentPacks.putShared('GulaSlotType', GulaSlotType)
    ContentPacks.putShared('ContainerSlotType', ContainerSlotType)
    ContentPacks.putShared('DigestSlotType', DigestSlotType)


    ContentPacks.putShared('LuckHover', LuckHover)
    ContentPacks.putShared('AlwaysEatHover', AlwaysEatHover)
    ContentPacks.putShared('DirectlyNearbyOrganHover', DirectlyNearbyOrganHover)
    ContentPacks.putShared('NearbyOrganHover', NearbyOrganHover)
    ContentPacks.putShared('DiagonalOrganHover', DiagonalOrganHover)
    ContentPacks.putShared('KeyActiveHover', KeyActiveHover)
    ContentPacks.putShared('FrozenHover', FrozenHover)
    ContentPacks.putShared('SoildCoreHover', SoildCoreHover)
    ContentPacks.putShared('VitaToxinsHover', VitaToxinsHover)
    ContentPacks.putShared('PutridToxinsHover', PutridToxinsHover)
    ContentPacks.putShared('MagicOverloadHover', MagicOverloadHover)
    ContentPacks.putShared('ChestcavityTypeHover', ChestcavityTypeHover)
    ContentPacks.putShared('RevolutionMachineTypeHover', RevolutionMachineTypeHover)
    ContentPacks.putShared('FunctionalEntityTypeHover', FunctionalEntityTypeHover)
    ContentPacks.putShared('GulaTypeHover', GulaTypeHover)
    ContentPacks.putShared('RoseTypeHover', RoseTypeHover)
    ContentPacks.putShared('Player17TypeHover', Player17TypeHover)
    ContentPacks.putShared('Player21TypeHover', Player21TypeHover)
    ContentPacks.putShared('Player25TypeHover', Player25TypeHover)
    ContentPacks.putShared('Player27TypeHover', Player27TypeHover)
    ContentPacks.putShared('TimeStabilityHover', TimeStabilityHover)
    ContentPacks.putShared('UnstableHover', UnstableHover)
    ContentPacks.putShared('ExtremeStrengthHover', ExtremeStrengthHover)
    ContentPacks.putShared('ExtremeFitnessHover', ExtremeFitnessHover)
    ContentPacks.putShared('FrostShieldHover', FrostShieldHover)
    ContentPacks.putShared('BasicTumorScoreHover', BasicTumorScoreHover)
    ContentPacks.putShared('PotentialTumorScoreHover', PotentialTumorScoreHover)
}