
[HoningConfig]
	HeadHoneBase = 450
	HeadHoneMultiplier = 200
	ChestHoneBase = 450
	ChestHoneMultiplier = 200
	LegsHoneBase = 450
	LegsHoneMultiplier = 200
	FeetHoneBase = 450
	FeetHoneMultiplier = 200

