#Whether to use the dark theme for the Vault UI. If false, uses a vanilla-like light theme.
darkMode = false
#The default sort mode for the Vault UI.
#Allowed Values: COUNT, LAST_EDITED, NAME_ID, NAME
sortMode = "LAST_EDITED"
#Whether to use colors from Create: Vibrant Vaults in the UI.
vibrantColors = true
#Whether to sync the Vault UI search bar with JEI/EMI search bar.
jeiSync = true

