// priority: 500
RegistryOrgan('kubejs:fireproof_appendix').addScore('chestcavity:luck', 0.5).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_intestine').addScore('chestcavity:nutrition', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_heart').addScore('chestcavity:health', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_kidney').addScore('chestcavity:filtration', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_liver').addScore('chestcavity:detoxification', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_lung').addScore('chestcavity:breath_recovery', 0.75).addScore('chestcavity:breath_capacity', 0.75).addScore('chestcavity:endurance', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_muscle').addScore('chestcavity:strength', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_rib').addScore('chestcavity:defense', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_spine').addScore('chestcavity:nerves', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_spleen').addScore('chestcavity:metabolism', 0.75).addScore('chestcavity:fire_resistant', 0.5)
RegistryOrgan('kubejs:fireproof_stomach').addScore('chestcavity:digestion', 0.75).addScore('chestcavity:fire_resistant', 0.5)
