// priority: 502
const IronNutrientsOrganDataWeightModel = new WeightRandomModel()
    .addWeightRandom({ name: 'chestcavity:defense', mean: 2, sigma: 1 }, 15)
    .addWeightRandom({ name: 'chestcavity:strength', mean: 2, sigma: 1 }, 15)
    .addWeightRandom({ name: 'kubejs:proliferation_efficiency', mean: 2, sigma: 1 }, 30)
    .addWeightRandom({ name: 'kubejs:genetic_stability', mean: 2, sigma: 1 }, 15)
    .addWeightRandom({ name: 'kubejs:iron_refine_efficiency', mean: 2, sigma: 1 }, 30)

const IronNutrientsPotentialOrganDataWeightModel = new WeightRandomModel()
    .addWeightRandom({ name: 'kubejs:extreme_fitness', mean: 1, sigma: 0.5 }, 30)
    .addWeightRandom({ name: 'kubejs:extreme_strength', mean: 1, sigma: 0.5 }, 30)
    .addWeightRandom({ name: 'kubejs:crit_damage', mean: 0.5, sigma: 0.5 }, 10)
    .addWeightRandom({ name: 'kubejs:crit_chance', mean: 0.5, sigma: 0.5 }, 10)
    .addWeightRandom({ name: 'chestcavity:health', mean: 1, sigma: 0.5 }, 10)
    .addWeightRandom({ name: 'chestcavity:endurance', mean: 0.5, sigma: 0.5 }, 10)
    .addWeightRandom({ name: 'chestcavity:fire_resistant', mean: 0.5, sigma: 0.5 }, 5)
    .addWeightRandom({ name: 'chestcavity:knockback_resistant', mean: 0.5, sigma: 0.5 }, 5)
    .addWeightRandom({ name: 'kubejs:dragon_blood', mean: 0.5, sigma: 0.5 }, 5)

registryUnformedTumorFluidConfig(
    new UnformedTumorFluidConfigModel('kubejs:iron_nutrients_fluid')
        .setPotentialOrganDataModel(IronNutrientsPotentialOrganDataWeightModel)
        .setOrganDataModel(IronNutrientsOrganDataWeightModel)
        .setOrganDataCount(3)
        .setPotentialOrganDataCount(1)
)