// priority: 800
ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:simple_culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.simple_culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.simple_culture_medium.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.culture_medium.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.culture_medium.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:mutation_culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.mutation_culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.mutation_culture_medium.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:mixed_culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.mixed_culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.mixed_culture_medium.shift.1'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:proliferation_culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.proliferation_culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.proliferation_culture_medium.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.proliferation_culture_medium.shift.2'))
)

ApplyMultiStateTooltip(new MultiStateTooltip('kubejs:refined_culture_medium')
    .setShiftDescription(Text.translatable('tooltips.kubejs.tool.shift.1'))
    .setShiftHoldingDescription(Text.translatable('tooltips.kubejs.tool.shift_holding.1'))
    .addDefault(Text.translatable('tooltips.kubejs.refined_culture_medium.default.1').gray())
    .addShift(Text.translatable('tooltips.kubejs.refined_culture_medium.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.refined_culture_medium.shift.2'))
    .addShift(Text.translatable('tooltips.kubejs.refined_culture_medium.shift.3'))
)