// priority: 500
ServerEvents.recipes(event => {
    const { tconstruct } = event.recipes
    //无流体物品
    //tconstruct.material('kubejs:','')
    tconstruct.material('kubejs:living_flesh', 'biomancy:living_flesh')
    tconstruct.material('kubejs:creator_mix', 'biomancy:creator_mix')
    tconstruct.material('kubejs:acid_splatter', 'biomancy:acid_splatter')
    tconstruct.material('kubejs:koboleton_bone', 'cataclysm:koboleton_bone')
    tconstruct.material('kubejs:mob_marrow', 'biomancy:mob_marrow')
    tconstruct.material('kubejs:bone_fragments', 'biomancy:bone_fragments')
    tconstruct.material('kubejs:tough_fibers', 'biomancy:tough_fibers') 
    tconstruct.material('kubejs:elastic_fibers', 'biomancy:elastic_fibers')  
    tconstruct.material('kubejs:withered_mob_marrow', 'biomancy:withered_mob_marrow') 
    tconstruct.material('kubejs:magebloom_fiber', 'ars_nouveau:magebloom_fiber') 
    tconstruct.material('kubejs:mob_sinew', 'biomancy:mob_sinew') 
    tconstruct.material('kubejs:nutrients', 'biomancy:nutrients') 
    tconstruct.material('kubejs:organic_matter', 'biomancy:organic_matter') 
    tconstruct.material('kubejs:regenerative_fluid', 'biomancy:regenerative_fluid') 
    tconstruct.material('kubejs:essence_of_the_storm','cataclysm:essence_of_the_storm')
    tconstruct.material('kubejs:flesh_bits','biomancy:flesh_bits')
    tconstruct.material('kubejs:lacrima','cataclysm:lacrima')
    tconstruct.material('kubejs:mineral_fragment','biomancy:mineral_fragment')
    tconstruct.material('kubejs:gem_fragments','biomancy:gem_fragments')
    tconstruct.material('kubejs:source_gem','ars_nouveau:source_gem')
    tconstruct.material('kubejs:toxin_extract','biomancy:toxin_extract')
    tconstruct.material('kubejs:bio_lumens','biomancy:bio_lumens')
    tconstruct.material('kubejs:exotic_dust','biomancy:exotic_dust')
    tconstruct.material('kubejs:hormone_secretion','biomancy:hormone_secretion')
    tconstruct.material('kubejs:withering_ooze','biomancy:withering_ooze')
    tconstruct.material('kubejs:mob_fang','biomancy:mob_fang')
    tconstruct.material('kubejs:mob_claw','biomancy:mob_claw')
    tconstruct.material('kubejs:wilden_horn','ars_nouveau:wilden_horn')
    tconstruct.material('kubejs:wilden_spike','ars_nouveau:wilden_spike')
    tconstruct.material('kubejs:wilden_wing','ars_nouveau:wilden_wing')
    tconstruct.material('kubejs:mob_gland','biomancy:mob_gland')
    tconstruct.material('kubejs:volatile_gland','biomancy:volatile_gland')
    tconstruct.material('kubejs:toxin_gland','biomancy:toxin_gland')
    tconstruct.material('kubejs:volatile_fluid','biomancy:volatile_fluid')
    tconstruct.material('kubejs:bile','biomancy:bile')
    tconstruct.material('kubejs:glintstone','kubejs:glintstone')
    tconstruct.material('kubejs:magma','minecraft:magma_block')
})
    